spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.opjccqmsuyinvypfefkk
spring.datasource.password=jonatanDj1.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ARMI Official Integration Configuration
armi.api.baseUrl=https://armi-services-support-rakdtiqnya-uc.a.run.app/support
armi.api.token=6IiKv72bT9
